# server port
port: 13000

# s3 storage config
s3:
  accessDomain: "http://127.0.0.1:30002"
  bucket: "cae-cms"
  region: "us-east-1"
  endpoint: "http://127.0.0.1:30002"
  forcePathStyle: true
  accessKeyId: "cae-cms"
  secretAccessKey: "30cc1mu5fYJkF3L2j2iY"

# db config
relationDB:
    type: 'postgresql' # mysql | postgresql
    hostsPool:
      - postgres:5432
    dbName: "cae-cms"
    dbUser: "demo"
    dbPwd: "abc123!"

redis:
  # type: "standalone" # standalone-单机，sentinel-哨兵
  # redisServer: "redis-service"
  # redisPort: 6379
  # redisPassword: "DcT4ahiDUVZeMU1xMAiW"
  # redisdb: 5
  # name: "" # master group name
  # sentinels:
  #   - host: ""
  #     port: 0
  # sentinelPassword: ""

  type: "standalone" # standalone-单机，sentinel-哨兵
  redisServer: "127.0.0.1"
  redisPort: 30004
  redisPassword: "DcT4ahiDUVZeMU1xMAiW"
  redisdb: 5
  name: "" # master group name
  sentinels:
    - host: ""
      port: 0
  sentinelPassword: ""