apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner  
  labels:
    app: nfs-client-provisioner
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner  
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner #与nfs-rbac.yaml文件中一致
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-client     #与nfs-storageClass.yaml中保持一致
            - name: NFS_SERVER
              value: docker-desktop #真实nfs服务端ip
            - name: NFS_PATH
              value: /data/nfs            #挂载的目录
      volumes:
        - name: nfs-client-root
          nfs:
            server: docker-desktop  #真实nfs服务端ip
            path: /data/nfs              #挂载的目录
