apiVersion: v1
kind: ConfigMap
metadata:
  name: cae-cms-app-config
  namespace: cae-cms
data:
  config.yaml: |
    port: 13000

    s3:
      accessDomain: "http://127.0.0.1:30002"
      bucket: "cae-cms"
      region: "us-east-1"
      endpoint: "http://minio-service:9000"
      forcePathStyle: true
      accessKeyId: "cae-cms"
      secretAccessKey: "30cc1mu5fYJkF3L2j2iY"

    relationDB:
        type: 'postgresql' # mysql | postgresql
        hostsPool:
          - postgres-service:5432
        dbName: "cae-cms"
        dbUser: "cae-cms"
        dbPwd: "90CpY0GGa8Q5nmg5LKZD"

    redis:
      type: "standalone" # standalone-单机，sentinel-哨兵
      redisServer: "redis-service"
      redisPort: 6379
      redisPassword: "DcT4ahiDUVZeMU1xMAiW"
      redisdb: 5
      name: ""
      sentinels:
        - host: ""
          port: 0
      sentinelPassword: ""


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cae-cms
  name: cae-cms
spec:
  selector:
    matchLabels:
      app: cae-cms
  template:
    metadata:
      labels:
        app: cae-cms
    spec:
      containers:
        - name: cae-cms
          image: cae-cms:v1.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 13000
          volumeMounts:
            - name: app-config
              mountPath: /app/dist/app-config
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /v1/health
              port: 13000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: app-config
          configMap:
            name: cae-cms-app-config

---

apiVersion: v1
kind: Service
metadata:
  name: cae-cms
  namespace: cae-cms
spec:
  selector:
    app: cae-cms
  type: NodePort
  ports:
  - port: 13000
    targetPort: 13000
    nodePort: 30005