apiVersion: v1
kind: ConfigMap
metadata:
  name: cae-cms-app-config
  namespace: cae-cms
data:
  config.yaml: |
    port: 13000

    s3:
      accessDomain: "http://127.0.0.1:30002"
      bucket: "cae-cms"
      region: "us-east-1"
      endpoint: "http://minio-service:9000"
      forcePathStyle: true
      accessKeyId: "cae-cms"
      secretAccessKey: "30cc1mu5fYJkF3L2j2iY"

    relationDB:
        type: 'postgresql' # mysql | postgresql
        hostsPool:
          - postgres-service:5432
        dbName: "cae-cms"
        dbUser: "cae-cms"
        dbPwd: "90CpY0GGa8Q5nmg5LKZD"

    redis:
      type: "standalone" # standalone-单机，sentinel-哨兵
      redisServer: "redis-service"
      redisPort: 6379
      redisPassword: "DcT4ahiDUVZeMU1xMAiW"
      redisdb: 5
      name: ""
      sentinels:
        - host: ""
          port: 0
      sentinelPassword: ""

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cae-cms-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/e/workspace/local-pv/cae-cms-logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cae-cms-logs-pvc
  namespace: cae-cms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cae-cms
  name: cae-cms
spec:
  selector:
    matchLabels:
      app: cae-cms
  template:
    metadata:
      labels:
        app: cae-cms
    spec:
      containers:
        - name: cae-cms
          image: cae-cms:v1.3.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 13000
          volumeMounts:
            - name: app-config
              mountPath: /app/dist/app-config
            - name: cae-cms-logs
              mountPath: /app/logs
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 13000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 13000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: app-config
          configMap:
            name: cae-cms-app-config
        - name: cae-cms-logs
          persistentVolumeClaim:
            claimName: cae-cms-logs-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: cae-cms
  namespace: cae-cms
spec:
  selector:
    app: cae-cms
  type: NodePort
  ports:
  - port: 13000
    targetPort: 13000
    nodePort: 30005